MAX_LENGTH_NAME = 150
MAX_LENGTH_TOKEN = 20
MAX_LENGTH_CONFITMATION_CODE = 100
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_PASSWORD = 128
MAX_LENGTH_TAG = 50
MAX_LENGTH_TEXT = 30
MAX_LENGTH_UNIT = 50
MAX_LENGTH_TITLE = 255
MAX_LENGTH_URL = 200
MAX_LENGTH_LINK = 6
USER = 'user'
ADMIN = 'admin'
ROLES = (
        ('user', 'Пользователь'),
        ('admin', 'Администратор'),
)
