# Generated by Django 4.2.14 on 2024-08-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
