# Generated by Django 4.2.14 on 2024-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='short_link',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
