# Generated by Django 4.2.14 on 2024-08-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipeingredient_short_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='short_link',
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
