# Generated by Django 4.2.14 on 2024-08-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка на авторов', 'verbose_name_plural': 'Подписки на авторов'},
        ),
    ]
