# Generated by Django 4.2.14 on 2024-08-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-id'], 'verbose_name': 'Подписка на авторов', 'verbose_name_plural': 'Подписки на авторов'},
        ),
    ]
